apiVersion: v1
kind: Namespace
metadata:
 name: myspace
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: compute-quota
 namespace: myspace
spec:
 hard:
   requests.cpu: "3"
   requests.memory: 3Gi
   limits.cpu: "4"
   limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: object-quota
 namespace: myspace
spec:
 hard:
   configmaps: "10"
   persistentvolumeclaims: "4"
   replicationcontrollers: "20"
   secrets: "10"
   services: "10"
   services.loadbalancers: "2"
